In [1]:
import pandas as pd

In [2]:
headers = ['Date Time', 'Link', 'Energy consumption', 'Speed', 'VID']  # Replace with your actual column names
data = pd.read_csv('link_avg_speed - Copy.csv', header = None, names = headers)

In [3]:
data.head()

Date Time  Link  Energy consumption      Speed  VID
0  01/11/2017 08:00     1            0.467553  38.971429  418
1  01/11/2017 09:00     1            0.467553  38.971429  418
2  01/11/2017 10:00     1            0.467553  38.971429  418
3  01/11/2017 11:00     1            0.467553  38.971429  418
4  01/11/2017 12:00     1            0.467553  38.971429  418

In [4]:
x = data[data['Energy consumption'] > 4.1]
y = x[x['Energy consumption'] < 4.2]
y

Date Time  Link  Energy consumption      Speed  VID
290396  23/11/2017 12:00   798            4.176580  78.285714  344
290698  18/11/2017 15:00   799            4.137569  60.062500  116

In [5]:
vehicleType = pd.read_excel('VED_Static_Data_ICE&HEV&PHEV&EV.xlsx')

In [6]:
vehicleType

VehId Vehicle Type Vehicle Class Engine Configuration & Displacement   
0        2          ICE           Car                       4-FI 2.0L T/C  \
1        5          HEV           Car                 4-GAS/ELECTRIC 2.0L   
2        7          ICE           SUV                           6-FI 3.6L   
3        8          ICE           Car                           4-FI 1.5L   
4       12          ICE           Car                           4-FI 1.8L   
..     ...          ...           ...                                 ...   
378    554         PHEV           Car                 4-GAS/ELECTRIC 1.4L   
379    560         PHEV           Car                 4-GAS/ELECTRIC 1.8L   
380    561         PHEV           Car                 4-GAS/ELECTRIC 2.0L   
381    567         PHEV           Car                 4-GAS/ELECTRIC 1.4L   
382    569         PHEV           Car                 4-GAS/ELECTRIC 1.4L   

    Transmission Drive Wheels Generalized_Weight  
0        NO DATA      NO DATA               3500  
1        NO DATA      NO DATA               3500  
2      AUTOMATIC      NO DATA               4500  
3    5-SP MANUAL      NO DATA               2500  
4        NO DATA      NO DATA               2500  
..           ...          ...                ...  
378      NO DATA          FWD               4000  
379          CVT          FWD               3000  
380          CVT          FWD               4000  
381      NO DATA          FWD               4000  
382      NO DATA          FWD               4000  

[383 rows x 7 columns]

In [43]:
electricV = vehicleType[vehicleType['Vehicle Type'].str.contains('EV')]

In [44]:
electricV.head()

VehId Vehicle Type Vehicle Class Engine Configuration & Displacement   
1       5          HEV           Car                 4-GAS/ELECTRIC 2.0L  \
7     115          HEV       NO DATA                 4-GAS/ELECTRIC 2.5L   
12    124          HEV       NO DATA                 4-GAS/ELECTRIC 1.8L   
13    125          HEV       NO DATA                 4-GAS/ELECTRIC 2.4L   
33    150          HEV       NO DATA                 4-FI 1.3L GAS/ELEC.   

   Transmission Drive Wheels Generalized_Weight  
1       NO DATA      NO DATA               3500  
7       NO DATA      NO DATA               3500  
12      NO DATA      NO DATA               3000  
13      NO DATA      NO DATA               3500  
33          CVT      NO DATA               2500

In [45]:
vIds = electricV['VehId']

In [46]:
vIds

1        5
7      115
12     124
13     125
33     150
      ... 
378    554
379    560
380    561
381    567
382    569
Name: VehId, Length: 119, dtype: int64

In [47]:
is_in_list = data['VID'].isin(vIds)

In [48]:
is_in_list

0          True
1          True
2          True
3          True
4          True
          ...  
363991    False
363992    False
363993    False
363994    False
363995    False
Name: VID, Length: 363996, dtype: bool

In [49]:
filtered_data = data[is_in_list]

In [50]:
filtered_data

Date Time  Link  Energy consumption      Speed  VID
0       01/11/2017 08:00     1            0.467553  38.971429  418
1       01/11/2017 09:00     1            0.467553  38.971429  418
2       01/11/2017 10:00     1            0.467553  38.971429  418
3       01/11/2017 11:00     1            0.467553  38.971429  418
4       01/11/2017 12:00     1            0.467553  38.971429  418
...                  ...   ...                 ...        ...  ...
314123  28/11/2017 15:00   863            0.351419  99.424211  550
314124  28/11/2017 16:00   863            0.703902  27.657895  374
314125  28/11/2017 17:00   863            0.000000  97.024127  545
314126  28/11/2017 18:00   863            0.000000  97.024127  545
314127  28/11/2017 19:00   863            0.000000  97.024127  545

[160647 rows x 5 columns]

In [51]:
data

Date Time  Link  Energy consumption      Speed  VID
0       01/11/2017 08:00     1            0.467553  38.971429  418
1       01/11/2017 09:00     1            0.467553  38.971429  418
2       01/11/2017 10:00     1            0.467553  38.971429  418
3       01/11/2017 11:00     1            0.467553  38.971429  418
4       01/11/2017 12:00     1            0.467553  38.971429  418
...                  ...   ...                 ...        ...  ...
363991  28/11/2017 16:00  1000            0.414542  33.535545  185
363992  28/11/2017 17:00  1000            0.414542  33.535545  185
363993  28/11/2017 18:00  1000            0.414542  33.535545  185
363994  28/11/2017 19:00  1000            0.414542  33.535545  185
363995  28/11/2017 20:00  1000            0.414542  33.535545  185

[363996 rows x 5 columns]

In [1]:
import tensorflow as tf
import numpy as np

# Set the random seed for reproducibility
np.random.seed(42)

# Create a random tensor with shape (955, 12, 2)
random_tensor = tf.constant(np.random.rand(955, 12, 2), dtype=tf.float32)

# Print the shape and the first few elements of the tensor
print(random_tensor.shape)
print(random_tensor[:3, :3, :])

(955, 12, 2)
tf.Tensor(
[[[0.37454012 0.9507143 ]
  [0.7319939  0.5986585 ]
  [0.15601864 0.15599452]]

 [[0.45606998 0.785176  ]
  [0.19967379 0.5142344 ]
  [0.59241456 0.04645041]]

 [[0.54671025 0.18485446]
  [0.96958464 0.77513283]
  [0.93949896 0.89482737]]], shape=(3, 3, 2), dtype=float32)


In [3]:
output_tensor = tf.reshape(random_tensor, [955, 6, 4])

In [4]:
output_tensor.shape

TensorShape([955, 6, 4])

In [5]:
output_tensor

<tf.Tensor: shape=(955, 6, 4), dtype=float32, numpy=
array([[[0.37454012, 0.9507143 , 0.7319939 , 0.5986585 ],
        [0.15601864, 0.15599452, 0.05808361, 0.8661761 ],
        [0.601115  , 0.7080726 , 0.02058449, 0.96990985],
        [0.83244264, 0.21233912, 0.18182497, 0.1834045 ],
        [0.30424225, 0.52475643, 0.43194503, 0.29122913],
        [0.6118529 , 0.13949387, 0.29214466, 0.36636186]],

       [[0.45606998, 0.785176  , 0.19967379, 0.5142344 ],
        [0.59241456, 0.04645041, 0.60754484, 0.17052412],
        [0.06505159, 0.94888556, 0.965632  , 0.80839735],
        [0.30461377, 0.09767211, 0.684233  , 0.4401525 ],
        [0.12203824, 0.4951769 , 0.03438852, 0.9093204 ],
        [0.25877997, 0.66252226, 0.31171107, 0.52006805]],

       [[0.54671025, 0.18485446, 0.96958464, 0.77513283],
        [0.93949896, 0.89482737, 0.5979    , 0.9218742 ],
        [0.08849251, 0.19598286, 0.04522729, 0.32533032],
        [0.3886773 , 0.27134904, 0.8287375 , 0.35675332],
        [0.2809